### ISSUE TITLE
Version (-v ) command fails with error 

### ISSUE THREAD

**Issue by derselben** [infopulse/KDC#1]
```
PS C:\Users\pavlo> kdc -v
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pavlo\AppData\Local\Programs\Python\Python312\Scripts\kdc.exe\__main__.py", line 7, in <module>
  File "C:\Users\pavlo\AppData\Local\Programs\Python\Python312\Lib\site-packages\kdc\main.py", line 194, in main
    app()
  File "C:\Users\pavlo\AppData\Local\Programs\Python\Python312\Lib\site-packages\kdc\main.py", line 71, in app
    version = get_version_from_pyproject()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavlo\AppData\Local\Programs\Python\Python312\Lib\site-packages\kdc\config.py", line 94, in get_version_from_pyproject
    data = toml.load("pyproject.toml")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavlo\AppData\Local\Programs\Python\Python312\Lib\site-packages\toml\decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pyproject.toml'
PS C:\Users\pavlo>
```

**Comment by derselben** [comment]
Fixed
